type Vehicle {
    id: ID!
    userId: Int
    plate: String
    licensePlate: String
    brand: String!
    model: String!
    year: Int
    color: String
    size_category: String
    sizeCategory: String
    fuelType: String
    vin: String
    isPrimary: Boolean
    createdAt: String
    updatedAt: String
}

type VehicleOutput {
  vehicle: Vehicle
  vehicles: [Vehicle!]
  hasError: Boolean!
  error: ErrorField
}

type ErrorField {
  field: String!
  message: String
}

type DeleteVehicleOutput {
  success: Boolean!
  error: String
}