changeLogFile=changelog/changelog.yaml

url=jdbc:postgresql://postgres:5432/leiriadetail_db

username=leiriadetail
password=leiriapassword

driver=org.postgresql.Driver

classpath=/liquibase/drivers/postgresql-42.7.10.jar