driver: org.postgresql.Driver
url: jdbc:postgresql://postgres:5432/leiriadetail_db
username: leiriadetail
password: leiriapassword

changeLogFile: changelog/db.changelog.xml
classpath: /liquibase/drivers/postgresql.jar