type Service {
    id: ID!
    name: String!
    description: String
    longDescription: String
    priceAB: Float!
    priceC: Float!
    priceDE: Float!
    durationMinutes: Int
    durationDetails: String
    packType: String
    icon: String
    includes: [String!]
    processSteps: [ProcessStep!]
    loyaltyPoints: Int
    availableExtras: [Service]
    steps: [ServiceStep]
}

type ServiceStep {
  stepOrder: Int!
  title: String!
  durationMinutes: Int!
}

type FullServiceDetails {
    id: ID
    name: String
    description: String
    priceAB: Float
    priceC: Float
    priceDE: Float
    durationMinutes: Int
    packType: String
    steps: [ServiceStep]
    extras: [Service]
}

type ProcessStep {
    step: Int!
    title: String!
    description: String!
}

type ErrorField {
    field: String
    message: String
}

type ServiceOutput {
    services: [Service!]
    message: String
    hasError: Boolean!
    error: ErrorField
}