type DispatchBooking {
    id: Int!
    clientId: Int
    vehicleId: Int
    clientName: String!
    clientPhone: String!
    service: String!
    vehicle: String!
    vehiclePlate: String!
    date: String!
    time: String!
    duration: String!
    status: String!
    bay: String
}

type Bay {
    id: String!
    name: String!
    bookings: [DispatchBooking!]!
}

type AppointmentsData {
    pending: [DispatchBooking!]!
    bays: [Bay!]!
}

type AppointmentsPayload {
    data: AppointmentsData
    errors: [Error!]!
}